version: '3'

services:
  app_euro:
    build: APP
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    restart: always
    depends_on:
        bdeurosportapp_1:
        condition: service_healty

  bdeurosportapp_1:
    image: mysql:8.0.33
    ports:
      - "3307:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_PASSWORD: root
        MYSQL_DATABASE: bdeurosportapp
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
      